export const TYPE_TOGGLE = 'TYPE_TOGGLE'
export const TYPE_PICKLIST = 'TYPE_PICKLIST'
export const TYPE_SLIDER = 'TYPE_SLIDER'

export const panelSetup = {}

export const PANEL_GRAPHS = 'PANEL_GRAPHS'
export const TOGGLE_ANIMATION = 'TOGGLE_ANIMATION'
export const SLIDER_ANIMATION_RATE = 'SLIDER_ANIMATION_RATE'
panelSetup[PANEL_GRAPHS] = [
  TOGGLE_ANIMATION,
  SLIDER_ANIMATION_RATE,
]
export const PANEL_WAVEFORM = 'PANEL_WAVEFORM'
export const SLIDER_WAVEFORM_ZOOM = 'SLIDER_WAVEFORM_ZOOM'
export const SLIDER_WAVEFORM_HEIGHT = 'SLIDER_WAVEFORM_HEIGHT'
panelSetup[PANEL_WAVEFORM] = [
  SLIDER_WAVEFORM_ZOOM,
  SLIDER_WAVEFORM_HEIGHT,
]
export const PANEL_SPECTRUM = 'PANEL_SPECTRUM'
export const TOGGLE_SPECTRUM_LOG = 'TOGGLE_SPECTRUM_LOG'
export const SLIDER_SPECTRUM_HEIGHT = 'SLIDER_SPECTRUM_HEIGHT'
export const SLIDER_SPECTRUM_MAX_FREQ = 'SLIDER_SPECTRUM_MAX_FREQ'
export const SLIDER_SPECTRUM_MIN_DB = 'SLIDER_SPECTRUM_MIN_DB'
panelSetup[PANEL_SPECTRUM] = [
  TOGGLE_SPECTRUM_LOG,
  SLIDER_SPECTRUM_HEIGHT,
  SLIDER_SPECTRUM_MAX_FREQ,
  SLIDER_SPECTRUM_MIN_DB,
]
export const getHeightSliderNameFromCanvasId = {
  waveform: SLIDER_WAVEFORM_HEIGHT,
  spectrum: SLIDER_SPECTRUM_HEIGHT
}

export const PANEL_MAIN = 'PANEL_MAIN'
export const TOGGLE_AUDIO = 'TOGGLE_AUDIO'
export const SLIDER_MIXER_GAIN = 'SLIDER_MIXER_GAIN'
export const PICK_SCALE = 'PICK_SCALE'
export const SLIDER_MAIN_FREQ = 'SLIDER_MAIN_FREQ'
export const PICK_MAIN_SHAPE = 'PICK_MAIN_SHAPE'
export const SLIDER_BASE_FREQ = 'SLIDER_BASE_FREQ'
export const SLIDER_MAIN_MULT = 'SLIDER_MAIN_MULT'
panelSetup[PANEL_MAIN] = [
  TOGGLE_AUDIO,
  SLIDER_MIXER_GAIN,
  PICK_SCALE,
  SLIDER_MAIN_FREQ,
  PICK_MAIN_SHAPE,
  SLIDER_BASE_FREQ,
  SLIDER_MAIN_MULT,
]

export const PANEL_DISTORT = 'PANEL_DISTORT'
export const TOGGLE_DISTORT_MODE = 'TOGGLE_DISTORT_MODE'
export const SLIDER_DISTORTION = 'SLIDER_DISTORTION'
panelSetup[PANEL_DISTORT] = [
  TOGGLE_DISTORT_MODE,
  SLIDER_DISTORTION,
]

export const PANEL_DELAY = 'PANEL_DELAY'
export const SLIDER_DELAY_VOL_PC = 'SLIDER_DELAY_VOL_PC'
export const SLIDER_DELAY_RES_L = 'SLIDER_DELAY_RES_L'
export const SLIDER_DELAY_RES_C = 'SLIDER_DELAY_RES_C'
export const SLIDER_DELAY_RES_R = 'SLIDER_DELAY_RES_R'
export const SLIDER_DELAY_CENTRE_PC = 'SLIDER_DELAY_CENTRE_PC'
panelSetup[PANEL_DELAY] = [
  SLIDER_DELAY_VOL_PC,
  SLIDER_DELAY_RES_L,
  SLIDER_DELAY_RES_C,
  SLIDER_DELAY_RES_R,
  SLIDER_DELAY_CENTRE_PC,
]

export const PANEL_MOD_A = 'PANEL_MOD_A'
export const PICK_MOD_SHAPE_A = 'PICK_MOD_SHAPE_A'
export const SLIDER_MOD_MULT_A = 'SLIDER_MOD_MULT_A'
export const SLIDER_MOD_IDX_A = 'SLIDER_MOD_IDX_A'
export const PICK_MOD2_SHAPE_A = 'PICK_MOD2_SHAPE_A'
export const SLIDER_MOD2_RATE_A = 'SLIDER_MOD2_RATE_A'
export const SLIDER_MOD2_IDX_A = 'SLIDER_MOD2_IDX_A'
panelSetup[PANEL_MOD_A] = [
  PICK_MOD_SHAPE_A,
  SLIDER_MOD_MULT_A,
  SLIDER_MOD_IDX_A,
  PICK_MOD2_SHAPE_A,
  SLIDER_MOD2_RATE_A,
  SLIDER_MOD2_IDX_A,
]

export const PANEL_MOD_B = 'PANEL_MOD_B'
export const PICK_MOD_SHAPE_B = 'PICK_MOD_SHAPE_B'
export const SLIDER_MOD_MULT_B = 'SLIDER_MOD_MULT_B'
export const SLIDER_MOD_IDX_B = 'SLIDER_MOD_IDX_B'
export const PICK_MOD2_SHAPE_B = 'PICK_MOD2_SHAPE_B'
export const SLIDER_MOD2_RATE_B = 'SLIDER_MOD2_RATE_B'
export const SLIDER_MOD2_IDX_B = 'SLIDER_MOD2_IDX_B'
panelSetup[PANEL_MOD_B] = [
  PICK_MOD_SHAPE_B,
  SLIDER_MOD_MULT_B,
  SLIDER_MOD_IDX_B,
  PICK_MOD2_SHAPE_B,
  SLIDER_MOD2_RATE_B,
  SLIDER_MOD2_IDX_B,
]

export const keyUpMap = {
  KeyS: TOGGLE_AUDIO,
  KeyA: TOGGLE_ANIMATION,
  KeyD: TOGGLE_DISTORT_MODE,
  KeyL: TOGGLE_SPECTRUM_LOG,
}
